### ISSUE TITLE
DOS line endings in current release (2.1.0)

### ISSUE THREAD

**Issue by eddiezane** [remixz/run-js#12]
Running `run-js` spits out `env: node\r: No such file or directory` on the current release (2.1.0).

Looks like this is fixed on the master branch.

**Comment by remixz** [comment]
Hmm... That's weird. I wrote the code for 2.1.0 and published 2.1.0 from Windows, and when I install that from npm, I do get that error. The weird thing though is that when I ran all the files on master through `dos2unix`, which gets rid of the `\r` line endings that Windows uses, none of them had that ending.

I've re-published this release as 2.1.1 from my Mac, and that fixed it. That means npm on Windows is doing something to those files.

**Comment by remixz** [comment]
I'll close this for now since it's not an issue anymore, but I definitely want to investigate this to see if it's an npm bug.

**Comment by remixz** [comment]
Looks like this has been known for a while: https://github.com/npm/npm/issues/2097 This might have actually been a git issue too, since it seems like git will rewrite line-endings when cloning. :neutral_face: 

In any case, it would definitely be nice if npm tried to handle this. If this problem baffled me, I can only imagine what it would be like for someone who's new to writing modules, and then finding out it only works on Windows without some hacky workarounds or access to a non-Windows machine.
